# Generated by Django 3.2.25 on 2024-04-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240423_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='technologies',
            new_name='techs',
        ),
    ]
