# Generated by Django 3.2.25 on 2024-05-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240501_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
