# Generated by Django 5.0.6 on 2024-05-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_studentfavoritecourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='assignemnt_files/'),
        ),
    ]
