# Generated by Django 5.0.6 on 2024-05-13 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_studentassignment_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
