# Generated by Django 5.0.6 on 2024-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_studentassignment_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='uploaded_coursework',
            field=models.FileField(null=True, upload_to='coursework_files/'),
        ),
    ]
