# Generated by Django 5.0.6 on 2024-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_studentassignment_uploaded_coursework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
